//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.coe.components.Image.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.coe.components.Image.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lens aperture..
        /// </summary>
        internal static string Aperture_Desc {
            get {
                return ResourceManager.GetString("Aperture_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aperture_Prop {
            get {
                return ResourceManager.GetString("Aperture_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string Aperture0 {
            get {
                return ResourceManager.GetString("Aperture0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Aperture1 {
            get {
                return ResourceManager.GetString("Aperture1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal program.
        /// </summary>
        internal static string Aperture2 {
            get {
                return ResourceManager.GetString("Aperture2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture priority.
        /// </summary>
        internal static string Aperture3 {
            get {
                return ResourceManager.GetString("Aperture3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter priority.
        /// </summary>
        internal static string Aperture4 {
            get {
                return ResourceManager.GetString("Aperture4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative program (biased toward depth of field).
        /// </summary>
        internal static string Aperture5 {
            get {
                return ResourceManager.GetString("Aperture5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action program (biased toward fast shutter speed).
        /// </summary>
        internal static string Aperture6 {
            get {
                return ResourceManager.GetString("Aperture6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait mode (for closeup photos with the background out of focus).
        /// </summary>
        internal static string Aperture7 {
            get {
                return ResourceManager.GetString("Aperture7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape mode (for landscape photos with the background in focus).
        /// </summary>
        internal static string Aperture8 {
            get {
                return ResourceManager.GetString("Aperture8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string ApertureDefault {
            get {
                return ResourceManager.GetString("ApertureDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of brightness..
        /// </summary>
        internal static string Brightness_Desc {
            get {
                return ResourceManager.GetString("Brightness_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Brightness_Prop {
            get {
                return ResourceManager.GetString("Brightness_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string Category_Camera {
            get {
                return ResourceManager.GetString("Category_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        internal static string Category_DateTime {
            get {
                return ResourceManager.GetString("Category_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIF.
        /// </summary>
        internal static string Category_EXIF {
            get {
                return ResourceManager.GetString("Category_EXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Category_File {
            get {
                return ResourceManager.GetString("Category_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related File Information.
        /// </summary>
        internal static string Category_FileInfo {
            get {
                return ResourceManager.GetString("Category_FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string Category_Flash {
            get {
                return ResourceManager.GetString("Category_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string Category_GPS {
            get {
                return ResourceManager.GetString("Category_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Configuration.
        /// </summary>
        internal static string Category_ImageConfiguration {
            get {
                return ResourceManager.GetString("Category_ImageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Data Characteristics.
        /// </summary>
        internal static string Category_ImgData {
            get {
                return ResourceManager.GetString("Category_ImgData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tags.
        /// </summary>
        internal static string Category_Other {
            get {
                return ResourceManager.GetString("Category_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        internal static string Category_UserInfo {
            get {
                return ResourceManager.GetString("Category_UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Category_Version {
            get {
                return ResourceManager.GetString("Category_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the color filter array (CFA) geometric pattern of the image sensor..
        /// </summary>
        internal static string CfaPattern_Desc {
            get {
                return ResourceManager.GetString("CfaPattern_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFA Pattern.
        /// </summary>
        internal static string CfaPattern_Prop {
            get {
                return ResourceManager.GetString("CfaPattern_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color space information..
        /// </summary>
        internal static string ColorSpace_Desc {
            get {
                return ResourceManager.GetString("ColorSpace_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color space information.
        /// </summary>
        internal static string ColorSpace_Prop {
            get {
                return ResourceManager.GetString("ColorSpace_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information specific to compressed data..
        /// </summary>
        internal static string ComponentsConfiguration_Desc {
            get {
                return ResourceManager.GetString("ComponentsConfiguration_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components configuration.
        /// </summary>
        internal static string ComponentsConfiguration_Prop {
            get {
                return ResourceManager.GetString("ComponentsConfiguration_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information specific to compressed data..
        /// </summary>
        internal static string CompressedBitsPerPixel_Desc {
            get {
                return ResourceManager.GetString("CompressedBitsPerPixel_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image compression mode.
        /// </summary>
        internal static string CompressedBitsPerPixel_Prop {
            get {
                return ResourceManager.GetString("CompressedBitsPerPixel_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the direction of contrast processing applied by the camera when the image was shot..
        /// </summary>
        internal static string Contrast_Desc {
            get {
                return ResourceManager.GetString("Contrast_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast_Prop {
            get {
                return ResourceManager.GetString("Contrast_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Contrast0 {
            get {
                return ResourceManager.GetString("Contrast0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string Contrast1 {
            get {
                return ResourceManager.GetString("Contrast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Contrast2 {
            get {
                return ResourceManager.GetString("Contrast2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string ContrastDefault {
            get {
                return ResourceManager.GetString("ContrastDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the use of special processing on image data, such as rendering geared to output. When special
        ///processing is performed, the reader is expected to disable or minimize any further processing..
        /// </summary>
        internal static string CustomRendered_Desc {
            get {
                return ResourceManager.GetString("CustomRendered_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom image processing.
        /// </summary>
        internal static string CustomRendered_Prop {
            get {
                return ResourceManager.GetString("CustomRendered_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal process.
        /// </summary>
        internal static string CustomRendered0 {
            get {
                return ResourceManager.GetString("CustomRendered0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom process.
        /// </summary>
        internal static string CustomRendered1 {
            get {
                return ResourceManager.GetString("CustomRendered1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string CustomRenderedDefault {
            get {
                return ResourceManager.GetString("CustomRenderedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the image was stored as digital data. .
        /// </summary>
        internal static string DateTimeDigitized_Desc {
            get {
                return ResourceManager.GetString("DateTimeDigitized_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date digitial data.
        /// </summary>
        internal static string DateTimeDigitized_Prop {
            get {
                return ResourceManager.GetString("DateTimeDigitized_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time when the original image data was generated..
        /// </summary>
        internal static string DateTimeOriginal_Desc {
            get {
                return ResourceManager.GetString("DateTimeOriginal_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date original data.
        /// </summary>
        internal static string DateTimeOriginal_Prop {
            get {
                return ResourceManager.GetString("DateTimeOriginal_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unkown.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates information on the picture-taking conditions of a particular camera model. The tag is used only to
        ///indicate the picture-taking conditions in the reader..
        /// </summary>
        internal static string DeviceSettingDescription_Desc {
            get {
                return ResourceManager.GetString("DeviceSettingDescription_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device setting description.
        /// </summary>
        internal static string DeviceSettingDescription_Prop {
            get {
                return ResourceManager.GetString("DeviceSettingDescription_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the digital zoom ratio when the image was shot. If the numerator of the recorded value is 0, this
        ///indicates that digital zoom was not used..
        /// </summary>
        internal static string DigitalZoomRatio_Desc {
            get {
                return ResourceManager.GetString("DigitalZoomRatio_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital zoom ratio.
        /// </summary>
        internal static string DigitalZoomRatio_Prop {
            get {
                return ResourceManager.GetString("DigitalZoomRatio_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manufacturer of the recording equipment..
        /// </summary>
        internal static string EquipMake_Desc {
            get {
                return ResourceManager.GetString("EquipMake_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment manufacturer.
        /// </summary>
        internal static string EquipMake_Prop {
            get {
                return ResourceManager.GetString("EquipMake_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model name or model number of the equipment..
        /// </summary>
        internal static string EquipModel_Desc {
            get {
                return ResourceManager.GetString("EquipModel_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment model.
        /// </summary>
        internal static string EquipModel_Prop {
            get {
                return ResourceManager.GetString("EquipModel_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of this standard supported..
        /// </summary>
        internal static string ExifVersion_Desc {
            get {
                return ResourceManager.GetString("ExifVersion_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exif version.
        /// </summary>
        internal static string ExifVersion_Prop {
            get {
                return ResourceManager.GetString("ExifVersion_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exposure bias..
        /// </summary>
        internal static string ExposureBias_Desc {
            get {
                return ResourceManager.GetString("ExposureBias_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Bias.
        /// </summary>
        internal static string ExposureBias_Prop {
            get {
                return ResourceManager.GetString("ExposureBias_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the exposure index selected on the camera or input device at the time the image is captured..
        /// </summary>
        internal static string ExposureIndex_Desc {
            get {
                return ResourceManager.GetString("ExposureIndex_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure index.
        /// </summary>
        internal static string ExposureIndex_Prop {
            get {
                return ResourceManager.GetString("ExposureIndex_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the exposure mode set when the image was shot..
        /// </summary>
        internal static string ExposureMode_Desc {
            get {
                return ResourceManager.GetString("ExposureMode_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure mode.
        /// </summary>
        internal static string ExposureMode_Prop {
            get {
                return ResourceManager.GetString("ExposureMode_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto exposure.
        /// </summary>
        internal static string ExposureMode0 {
            get {
                return ResourceManager.GetString("ExposureMode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual exposure.
        /// </summary>
        internal static string ExposureMode1 {
            get {
                return ResourceManager.GetString("ExposureMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto bracket.
        /// </summary>
        internal static string ExposureMode2 {
            get {
                return ResourceManager.GetString("ExposureMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string ExposureModeDefault {
            get {
                return ResourceManager.GetString("ExposureModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class of the program used by the camera to set exposure when the picture is taken..
        /// </summary>
        internal static string ExposureProgram_Desc {
            get {
                return ResourceManager.GetString("ExposureProgram_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure program.
        /// </summary>
        internal static string ExposureProgram_Prop {
            get {
                return ResourceManager.GetString("ExposureProgram_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure time, given in seconds (sec)..
        /// </summary>
        internal static string ExposureTime_Desc {
            get {
                return ResourceManager.GetString("ExposureTime_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Time.
        /// </summary>
        internal static string ExposureTime_Prop {
            get {
                return ResourceManager.GetString("ExposureTime_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path and Name of the image..
        /// </summary>
        internal static string FileName_Desc {
            get {
                return ResourceManager.GetString("FileName_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FileName_Prop {
            get {
                return ResourceManager.GetString("FileName_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual filesize in MB..
        /// </summary>
        internal static string FileSize_Desc {
            get {
                return ResourceManager.GetString("FileSize_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FileSize_Prop {
            get {
                return ResourceManager.GetString("FileSize_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the image source..
        /// </summary>
        internal static string FileSource_Desc {
            get {
                return ResourceManager.GetString("FileSource_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File source.
        /// </summary>
        internal static string FileSource_Prop {
            get {
                return ResourceManager.GetString("FileSource_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the image..
        /// </summary>
        internal static string FileType_Desc {
            get {
                return ResourceManager.GetString("FileType_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FileType_Prop {
            get {
                return ResourceManager.GetString("FileType_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash did not fire.
        /// </summary>
        internal static string Flash0 {
            get {
                return ResourceManager.GetString("Flash0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash fired.
        /// </summary>
        internal static string Flash1 {
            get {
                return ResourceManager.GetString("Flash1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flash function.
        /// </summary>
        internal static string Flash10 {
            get {
                return ResourceManager.GetString("Flash10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No red-eye reduction mode or unknown.
        /// </summary>
        internal static string Flash11 {
            get {
                return ResourceManager.GetString("Flash11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red-eye reduction supported.
        /// </summary>
        internal static string Flash12 {
            get {
                return ResourceManager.GetString("Flash12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No strobe return detection function.
        /// </summary>
        internal static string Flash2 {
            get {
                return ResourceManager.GetString("Flash2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe return light not detected.
        /// </summary>
        internal static string Flash3 {
            get {
                return ResourceManager.GetString("Flash3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe return light detected.
        /// </summary>
        internal static string Flash4 {
            get {
                return ResourceManager.GetString("Flash4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Flash5 {
            get {
                return ResourceManager.GetString("Flash5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory flash firing.
        /// </summary>
        internal static string Flash6 {
            get {
                return ResourceManager.GetString("Flash6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsory flash suppression.
        /// </summary>
        internal static string Flash7 {
            get {
                return ResourceManager.GetString("Flash7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode.
        /// </summary>
        internal static string Flash8 {
            get {
                return ResourceManager.GetString("Flash8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash function present.
        /// </summary>
        internal static string Flash9 {
            get {
                return ResourceManager.GetString("Flash9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string FlashDefault {
            get {
                return ResourceManager.GetString("FlashDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the flash fired..
        /// </summary>
        internal static string FlashFired_Desc {
            get {
                return ResourceManager.GetString("FlashFired_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash fired.
        /// </summary>
        internal static string FlashFired_Prop {
            get {
                return ResourceManager.GetString("FlashFired_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the presence of a flash function..
        /// </summary>
        internal static string FlashFunction_Desc {
            get {
                return ResourceManager.GetString("FlashFunction_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash function.
        /// </summary>
        internal static string FlashFunction_Prop {
            get {
                return ResourceManager.GetString("FlashFunction_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the camera&apos;s flash mode..
        /// </summary>
        internal static string FlashMode_Desc {
            get {
                return ResourceManager.GetString("FlashMode_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash mode.
        /// </summary>
        internal static string FlashMode_Prop {
            get {
                return ResourceManager.GetString("FlashMode_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flashpix format version supported by a FPXR file..
        /// </summary>
        internal static string FlashpixVersion_Desc {
            get {
                return ResourceManager.GetString("FlashpixVersion_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashpix version.
        /// </summary>
        internal static string FlashpixVersion_Prop {
            get {
                return ResourceManager.GetString("FlashpixVersion_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the camera&apos;s red-eye mode..
        /// </summary>
        internal static string FlashRedEye_Desc {
            get {
                return ResourceManager.GetString("FlashRedEye_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash red eye mode.
        /// </summary>
        internal static string FlashRedEye_Prop {
            get {
                return ResourceManager.GetString("FlashRedEye_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the status of returned light..
        /// </summary>
        internal static string FlashReturn_Desc {
            get {
                return ResourceManager.GetString("FlashReturn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash return.
        /// </summary>
        internal static string FlashReturn_Prop {
            get {
                return ResourceManager.GetString("FlashReturn_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The F number..
        /// </summary>
        internal static string FNumber_Desc {
            get {
                return ResourceManager.GetString("FNumber_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-Number.
        /// </summary>
        internal static string FNumber_Prop {
            get {
                return ResourceManager.GetString("FNumber_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual focal length of the lens, in mm..
        /// </summary>
        internal static string FocalLength_Desc {
            get {
                return ResourceManager.GetString("FocalLength_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lens focal length.
        /// </summary>
        internal static string FocalLength_Prop {
            get {
                return ResourceManager.GetString("FocalLength_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the equivalent focal length assuming a 35mm film camera, in mm. A value of 0 means the focal
        ///length is unknown. Note that this tag differs from the FocalLength tag..
        /// </summary>
        internal static string FocalLengthIn35mmFilm_Desc {
            get {
                return ResourceManager.GetString("FocalLengthIn35mmFilm_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal length in 35 mm film.
        /// </summary>
        internal static string FocalLengthIn35mmFilm_Prop {
            get {
                return ResourceManager.GetString("FocalLengthIn35mmFilm_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the unit for measuring FocalPlaneXResolution and FocalPlaneYResolution..
        /// </summary>
        internal static string FocalPlaneResolutionUnit_Desc {
            get {
                return ResourceManager.GetString("FocalPlaneResolutionUnit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal plane resolution unit.
        /// </summary>
        internal static string FocalPlaneResolutionUnit_Prop {
            get {
                return ResourceManager.GetString("FocalPlaneResolutionUnit_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the number of pixels in the image width (X) direction per FocalPlaneResolutionUnit..
        /// </summary>
        internal static string FocalPlaneXResolution_Desc {
            get {
                return ResourceManager.GetString("FocalPlaneXResolution_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal plane X resolution.
        /// </summary>
        internal static string FocalPlaneXResolution_Prop {
            get {
                return ResourceManager.GetString("FocalPlaneXResolution_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the number of pixels in the image width (Y) direction per FocalPlaneResolutionUnit..
        /// </summary>
        internal static string FocalPlaneYResolution_Desc {
            get {
                return ResourceManager.GetString("FocalPlaneYResolution_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal plane Y resolution.
        /// </summary>
        internal static string FocalPlaneYResolution_Prop {
            get {
                return ResourceManager.GetString("FocalPlaneYResolution_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the degree of overall image gain adjustment..
        /// </summary>
        internal static string GainControl_Desc {
            get {
                return ResourceManager.GetString("GainControl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain control.
        /// </summary>
        internal static string GainControl_Prop {
            get {
                return ResourceManager.GetString("GainControl_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string GainControl0 {
            get {
                return ResourceManager.GetString("GainControl0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low gain up.
        /// </summary>
        internal static string GainControl1 {
            get {
                return ResourceManager.GetString("GainControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High gain up.
        /// </summary>
        internal static string GainControl2 {
            get {
                return ResourceManager.GetString("GainControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low gain down.
        /// </summary>
        internal static string GainControl3 {
            get {
                return ResourceManager.GetString("GainControl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High gain down.
        /// </summary>
        internal static string GainControl4 {
            get {
                return ResourceManager.GetString("GainControl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string GainControlDefault {
            get {
                return ResourceManager.GetString("GainControlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS date..
        /// </summary>
        internal static string GpsDate_Desc {
            get {
                return ResourceManager.GetString("GpsDate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datestamp.
        /// </summary>
        internal static string GpsDate_Prop {
            get {
                return ResourceManager.GetString("GpsDate_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the GPS latitude..
        /// </summary>
        internal static string GpsLatitude_Desc {
            get {
                return ResourceManager.GetString("GpsLatitude_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string GpsLatitude_Prop {
            get {
                return ResourceManager.GetString("GpsLatitude_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the GPS longitude..
        /// </summary>
        internal static string GpsLongitude_Desc {
            get {
                return ResourceManager.GetString("GpsLongitude_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string GpsLongitude_Prop {
            get {
                return ResourceManager.GetString("GpsLongitude_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the geodetic survey data used by the GPS receiver..
        /// </summary>
        internal static string GpsMapDate_Desc {
            get {
                return ResourceManager.GetString("GpsMapDate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map date.
        /// </summary>
        internal static string GpsMapDate_Prop {
            get {
                return ResourceManager.GetString("GpsMapDate_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the status of the GPS receiver when the image is recorded..
        /// </summary>
        internal static string GpsStatus_Desc {
            get {
                return ResourceManager.GetString("GpsStatus_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string GpsStatus_Prop {
            get {
                return ResourceManager.GetString("GpsStatus_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time as coordinated universal time (UTC)..
        /// </summary>
        internal static string GpsTime_Desc {
            get {
                return ResourceManager.GetString("GpsTime_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string GpsTime_Prop {
            get {
                return ResourceManager.GetString("GpsTime_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the Global Positioning Systems (GPS) IFD..
        /// </summary>
        internal static string GpsVersion_Desc {
            get {
                return ResourceManager.GetString("GpsVersion_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string GpsVersion_Prop {
            get {
                return ResourceManager.GetString("GpsVersion_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSC.
        /// </summary>
        internal static string ImageSource3 {
            get {
                return ResourceManager.GetString("ImageSource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string ImageSourceDefault {
            get {
                return ResourceManager.GetString("ImageSourceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the ISO Speed and ISO Latitude of the camera or input device..
        /// </summary>
        internal static string ISOSpeed_Desc {
            get {
                return ResourceManager.GetString("ISOSpeed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Speed.
        /// </summary>
        internal static string ISOSpeed_Prop {
            get {
                return ResourceManager.GetString("ISOSpeed_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component not licensed.
        /// </summary>
        internal static string LicInvalid {
            get {
                return ResourceManager.GetString("LicInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kind of light source..
        /// </summary>
        internal static string LightSource_Desc {
            get {
                return ResourceManager.GetString("LightSource_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light source.
        /// </summary>
        internal static string LightSource_Prop {
            get {
                return ResourceManager.GetString("LightSource_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string LightSource0 {
            get {
                return ResourceManager.GetString("LightSource0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight.
        /// </summary>
        internal static string LightSource1 {
            get {
                return ResourceManager.GetString("LightSource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy weather.
        /// </summary>
        internal static string LightSource10 {
            get {
                return ResourceManager.GetString("LightSource10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shade.
        /// </summary>
        internal static string LightSource11 {
            get {
                return ResourceManager.GetString("LightSource11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daylight fluorescent (D 5700 – 7100K).
        /// </summary>
        internal static string LightSource12 {
            get {
                return ResourceManager.GetString("LightSource12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day white fluorescent (N 4600 – 5400K).
        /// </summary>
        internal static string LightSource13 {
            get {
                return ResourceManager.GetString("LightSource13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool white fluorescent (W 3900 – 4500K).
        /// </summary>
        internal static string LightSource14 {
            get {
                return ResourceManager.GetString("LightSource14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White fluorescent (WW 3200 – 3700K).
        /// </summary>
        internal static string LightSource15 {
            get {
                return ResourceManager.GetString("LightSource15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard light A.
        /// </summary>
        internal static string LightSource17 {
            get {
                return ResourceManager.GetString("LightSource17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard light B.
        /// </summary>
        internal static string LightSource18 {
            get {
                return ResourceManager.GetString("LightSource18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard light C.
        /// </summary>
        internal static string LightSource19 {
            get {
                return ResourceManager.GetString("LightSource19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorescent.
        /// </summary>
        internal static string LightSource2 {
            get {
                return ResourceManager.GetString("LightSource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D55.
        /// </summary>
        internal static string LightSource20 {
            get {
                return ResourceManager.GetString("LightSource20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D65.
        /// </summary>
        internal static string LightSource21 {
            get {
                return ResourceManager.GetString("LightSource21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D75.
        /// </summary>
        internal static string LightSource22 {
            get {
                return ResourceManager.GetString("LightSource22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D50.
        /// </summary>
        internal static string LightSource23 {
            get {
                return ResourceManager.GetString("LightSource23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO studio tungsten.
        /// </summary>
        internal static string LightSource24 {
            get {
                return ResourceManager.GetString("LightSource24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string LightSource255 {
            get {
                return ResourceManager.GetString("LightSource255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tungsten.
        /// </summary>
        internal static string LightSource3 {
            get {
                return ResourceManager.GetString("LightSource3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string LightSource4 {
            get {
                return ResourceManager.GetString("LightSource4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine weather.
        /// </summary>
        internal static string LightSource9 {
            get {
                return ResourceManager.GetString("LightSource9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string LightSourceDefault {
            get {
                return ResourceManager.GetString("LightSourceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag for manufacturers of Exif writers to record any desired information. The contents are up to the manufacturer..
        /// </summary>
        internal static string MakerNote_Desc {
            get {
                return ResourceManager.GetString("MakerNote_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactorer notes.
        /// </summary>
        internal static string MakerNote_Prop {
            get {
                return ResourceManager.GetString("MakerNote_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The smallest F number of the lens..
        /// </summary>
        internal static string MaxAperture_Desc {
            get {
                return ResourceManager.GetString("MaxAperture_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum lens aperture.
        /// </summary>
        internal static string MaxAperture_Prop {
            get {
                return ResourceManager.GetString("MaxAperture_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metering mode..
        /// </summary>
        internal static string MeteringMode_Desc {
            get {
                return ResourceManager.GetString("MeteringMode_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metering mode.
        /// </summary>
        internal static string MeteringMode_Prop {
            get {
                return ResourceManager.GetString("MeteringMode_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string MeteringMode0 {
            get {
                return ResourceManager.GetString("MeteringMode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string MeteringMode1 {
            get {
                return ResourceManager.GetString("MeteringMode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CenterWeightedAverage.
        /// </summary>
        internal static string MeteringMode2 {
            get {
                return ResourceManager.GetString("MeteringMode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string MeteringMode255 {
            get {
                return ResourceManager.GetString("MeteringMode255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot.
        /// </summary>
        internal static string MeteringMode3 {
            get {
                return ResourceManager.GetString("MeteringMode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSpot.
        /// </summary>
        internal static string MeteringMode4 {
            get {
                return ResourceManager.GetString("MeteringMode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string MeteringMode5 {
            get {
                return ResourceManager.GetString("MeteringMode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string MeteringMode6 {
            get {
                return ResourceManager.GetString("MeteringMode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string MeteringModeDefault {
            get {
                return ResourceManager.GetString("MeteringModeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the Opto-Electric Conversion Function..
        /// </summary>
        internal static string OECF_Desc {
            get {
                return ResourceManager.GetString("OECF_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OECF_Prop {
            get {
                return ResourceManager.GetString("OECF_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image orientation..
        /// </summary>
        internal static string Orientation_Desc {
            get {
                return ResourceManager.GetString("Orientation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Orientation_Prop {
            get {
                return ResourceManager.GetString("Orientation_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top / left side.
        /// </summary>
        internal static string Orientation1 {
            get {
                return ResourceManager.GetString("Orientation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top / right side.
        /// </summary>
        internal static string Orientation2 {
            get {
                return ResourceManager.GetString("Orientation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom / right side.
        /// </summary>
        internal static string Orientation3 {
            get {
                return ResourceManager.GetString("Orientation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottum / left side.
        /// </summary>
        internal static string Orientation4 {
            get {
                return ResourceManager.GetString("Orientation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left side / top.
        /// </summary>
        internal static string Orientation5 {
            get {
                return ResourceManager.GetString("Orientation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right side / top.
        /// </summary>
        internal static string Orientation6 {
            get {
                return ResourceManager.GetString("Orientation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right side / bottum.
        /// </summary>
        internal static string Orientation7 {
            get {
                return ResourceManager.GetString("Orientation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left side / buttom.
        /// </summary>
        internal static string Orientation8 {
            get {
                return ResourceManager.GetString("Orientation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string OrientationDefault {
            get {
                return ResourceManager.GetString("OrientationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid width of the meaningful image..
        /// </summary>
        internal static string PixelXDimension_Desc {
            get {
                return ResourceManager.GetString("PixelXDimension_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid image width.
        /// </summary>
        internal static string PixelXDimension_Prop {
            get {
                return ResourceManager.GetString("PixelXDimension_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid heigth of the meaningful image..
        /// </summary>
        internal static string PixelYDimension_Desc {
            get {
                return ResourceManager.GetString("PixelYDimension_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid image height.
        /// </summary>
        internal static string PixelYDimension_Prop {
            get {
                return ResourceManager.GetString("PixelYDimension_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag is used to record the name of an audio file related to the image..
        /// </summary>
        internal static string RelatedSoundFile_Desc {
            get {
                return ResourceManager.GetString("RelatedSoundFile_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related audio file.
        /// </summary>
        internal static string RelatedSoundFile_Prop {
            get {
                return ResourceManager.GetString("RelatedSoundFile_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure for the horizontal resolution and the vertical resolution..
        /// </summary>
        internal static string ResolutionUnit_Desc {
            get {
                return ResourceManager.GetString("ResolutionUnit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution unit.
        /// </summary>
        internal static string ResolutionUnit_Prop {
            get {
                return ResourceManager.GetString("ResolutionUnit_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string ResolutionUnit2 {
            get {
                return ResourceManager.GetString("ResolutionUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string ResolutionUnit3 {
            get {
                return ResourceManager.GetString("ResolutionUnit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no unit.
        /// </summary>
        internal static string ResolutionUnitDefault {
            get {
                return ResourceManager.GetString("ResolutionUnitDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the direction of saturation processing applied by the camera when the image was shot..
        /// </summary>
        internal static string Saturation_Desc {
            get {
                return ResourceManager.GetString("Saturation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        internal static string Saturation_Prop {
            get {
                return ResourceManager.GetString("Saturation_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Saturation0 {
            get {
                return ResourceManager.GetString("Saturation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low saturation.
        /// </summary>
        internal static string Saturation1 {
            get {
                return ResourceManager.GetString("Saturation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High saturation.
        /// </summary>
        internal static string Saturation2 {
            get {
                return ResourceManager.GetString("Saturation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string SaturationDefault {
            get {
                return ResourceManager.GetString("SaturationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the type of scene that was shot. It can also be used to record the mode in which the image was
        ///shot. Note that this differs from the scene type (SceneType) tag..
        /// </summary>
        internal static string SceneCaptureType_Desc {
            get {
                return ResourceManager.GetString("SceneCaptureType_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene capture type.
        /// </summary>
        internal static string SceneCaptureType_Prop {
            get {
                return ResourceManager.GetString("SceneCaptureType_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string SceneCaptureType0 {
            get {
                return ResourceManager.GetString("SceneCaptureType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string SceneCaptureType1 {
            get {
                return ResourceManager.GetString("SceneCaptureType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string SceneCaptureType2 {
            get {
                return ResourceManager.GetString("SceneCaptureType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night scene.
        /// </summary>
        internal static string SceneCaptureType3 {
            get {
                return ResourceManager.GetString("SceneCaptureType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string SceneCaptureTypeDefault {
            get {
                return ResourceManager.GetString("SceneCaptureTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the type of scene..
        /// </summary>
        internal static string SceneType_Desc {
            get {
                return ResourceManager.GetString("SceneType_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene type.
        /// </summary>
        internal static string SceneType_Prop {
            get {
                return ResourceManager.GetString("SceneType_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A directly photographed image.
        /// </summary>
        internal static string SceneType1 {
            get {
                return ResourceManager.GetString("SceneType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a directly photographed image.
        /// </summary>
        internal static string SceneTypeDefault {
            get {
                return ResourceManager.GetString("SceneTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the image sensor type on the camera or input device..
        /// </summary>
        internal static string SensingMethod_Desc {
            get {
                return ResourceManager.GetString("SensingMethod_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensing method.
        /// </summary>
        internal static string SensingMethod_Prop {
            get {
                return ResourceManager.GetString("SensingMethod_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not defined.
        /// </summary>
        internal static string SensingMethod1 {
            get {
                return ResourceManager.GetString("SensingMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-chip color area sensor.
        /// </summary>
        internal static string SensingMethod2 {
            get {
                return ResourceManager.GetString("SensingMethod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-chip color area sensor.
        /// </summary>
        internal static string SensingMethod3 {
            get {
                return ResourceManager.GetString("SensingMethod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-chip color area sensor.
        /// </summary>
        internal static string SensingMethod4 {
            get {
                return ResourceManager.GetString("SensingMethod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color sequential area sensor.
        /// </summary>
        internal static string SensingMethod5 {
            get {
                return ResourceManager.GetString("SensingMethod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trilinear sensor.
        /// </summary>
        internal static string SensingMethod7 {
            get {
                return ResourceManager.GetString("SensingMethod7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color sequential linear sensor.
        /// </summary>
        internal static string SensingMethod8 {
            get {
                return ResourceManager.GetString("SensingMethod8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string SensingMethodDefault {
            get {
                return ResourceManager.GetString("SensingMethodDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the direction of sharpness processing applied by the camera when the image was shot..
        /// </summary>
        internal static string Sharpness_Desc {
            get {
                return ResourceManager.GetString("Sharpness_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sharpness_Prop {
            get {
                return ResourceManager.GetString("Sharpness_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Sharpness0 {
            get {
                return ResourceManager.GetString("Sharpness0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string Sharpness1 {
            get {
                return ResourceManager.GetString("Sharpness1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Sharpness2 {
            get {
                return ResourceManager.GetString("Sharpness2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string SharpnessDefault {
            get {
                return ResourceManager.GetString("SharpnessDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter speed..
        /// </summary>
        internal static string ShutterSpeed_Desc {
            get {
                return ResourceManager.GetString("ShutterSpeed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Speed.
        /// </summary>
        internal static string ShutterSpeed_Prop {
            get {
                return ResourceManager.GetString("ShutterSpeed_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag records the name and version of the software or firmware of the camera or image input device used to generate the image. The detailed format is not specified, but it is recommended that the example shown below be followed..
        /// </summary>
        internal static string Software_Desc {
            get {
                return ResourceManager.GetString("Software_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Software_Prop {
            get {
                return ResourceManager.GetString("Software_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag records the camera or input device spatial frequency table..
        /// </summary>
        internal static string SpatialFrequencyResponse_Desc {
            get {
                return ResourceManager.GetString("SpatialFrequencyResponse_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial frequency response.
        /// </summary>
        internal static string SpatialFrequencyResponse_Prop {
            get {
                return ResourceManager.GetString("SpatialFrequencyResponse_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the spectral sensitivity of each channel of the camera used. The tag value is an ASCII string..
        /// </summary>
        internal static string SpectralSensitivity_Desc {
            get {
                return ResourceManager.GetString("SpectralSensitivity_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral sensitivity.
        /// </summary>
        internal static string SpectralSensitivity_Prop {
            get {
                return ResourceManager.GetString("SpectralSensitivity_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the location and area of the main subject in the overall scene..
        /// </summary>
        internal static string SubjectArea_Desc {
            get {
                return ResourceManager.GetString("SubjectArea_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject area.
        /// </summary>
        internal static string SubjectArea_Prop {
            get {
                return ResourceManager.GetString("SubjectArea_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance to the subject, given in meters..
        /// </summary>
        internal static string SubjectDistance_Desc {
            get {
                return ResourceManager.GetString("SubjectDistance_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject distance.
        /// </summary>
        internal static string SubjectDistance_Prop {
            get {
                return ResourceManager.GetString("SubjectDistance_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the distance to the subject..
        /// </summary>
        internal static string SubjectDistanceRange_Desc {
            get {
                return ResourceManager.GetString("SubjectDistanceRange_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject distance range.
        /// </summary>
        internal static string SubjectDistanceRange_Prop {
            get {
                return ResourceManager.GetString("SubjectDistanceRange_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string SubjectDistanceRange0 {
            get {
                return ResourceManager.GetString("SubjectDistanceRange0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string SubjectDistanceRange1 {
            get {
                return ResourceManager.GetString("SubjectDistanceRange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close view.
        /// </summary>
        internal static string SubjectDistanceRange2 {
            get {
                return ResourceManager.GetString("SubjectDistanceRange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distant view.
        /// </summary>
        internal static string SubjectDistanceRange3 {
            get {
                return ResourceManager.GetString("SubjectDistanceRange3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string SubjectDistanceRangeDefault {
            get {
                return ResourceManager.GetString("SubjectDistanceRangeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the location of the main subject in the scene..
        /// </summary>
        internal static string SubjectLocation_Desc {
            get {
                return ResourceManager.GetString("SubjectLocation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject location.
        /// </summary>
        internal static string SubjectLocation_Prop {
            get {
                return ResourceManager.GetString("SubjectLocation_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag for Exif users to write keywords or comments on the image besides those in ImageDescription..
        /// </summary>
        internal static string UserComment_Desc {
            get {
                return ResourceManager.GetString("UserComment_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User comments.
        /// </summary>
        internal static string UserComment_Prop {
            get {
                return ResourceManager.GetString("UserComment_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag indicates the white balance set when the image was shot..
        /// </summary>
        internal static string WhiteBalance_Desc {
            get {
                return ResourceManager.GetString("WhiteBalance_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White balance.
        /// </summary>
        internal static string WhiteBalance_Prop {
            get {
                return ResourceManager.GetString("WhiteBalance_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto white balance.
        /// </summary>
        internal static string WhiteBalance0 {
            get {
                return ResourceManager.GetString("WhiteBalance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual white balance.
        /// </summary>
        internal static string WhiteBalance1 {
            get {
                return ResourceManager.GetString("WhiteBalance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserved.
        /// </summary>
        internal static string WhiteBalanceDefault {
            get {
                return ResourceManager.GetString("WhiteBalanceDefault", resourceCulture);
            }
        }
    }
}
